// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import("naive-ui")["NButton"]
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import("naive-ui")["NDatePicker"]
    NInput: typeof import("naive-ui")["NInput"]
    NSpace: typeof import('naive-ui')['NSpace']
  }
}
